Added undocumented endpoints from current backend.
pulsar-edit/docs pull request #1
Opened 2022-07-28 00:17 UTC by confused-Techie

Added the endpoints not included in the original docs.

2022-08-06 19:59 UTC, kaosine requested changes
See my other comment not sure what happened

2022-08-06 23:42 UTC, confused-Techie commented on docs/src/content/atom-server-side-apis/index.md
>  ## Atom server-side APIs
Ill go ahead and make thos echanges tonight. Do agree its probably best to use Pulsar, not sure why I out Atom. But thats the thing these endpoints are not mentioned anywhere, only found them by studying all of the apm source. But glad it looks good. Additionally any edequete style youve implemented I can use for the undocumented endpoint warning? Or do you think its not needed

2022-08-07 00:17 UTC, kaosine commented on docs/src/content/atom-server-side-apis/index.md
>  ## Atom server-side APIs
I'm still more focused on getting the old docs to deploy that we'll end up rewriting imo if they no longer suit us. I still need to add the updated build instructions and everything. I'm definitely going to be running everything through Language tool/grammarly at the very least then ask for reviews here. 

But getting it to deploy(image path errors and I assume the `{{ #warning }}`  type tags that need to be replaced with `:::warning` iirc? I have to look up the documentation again for that. I just want to make things seem clear, especially if that means referencing our sunsetted upstream or making sure things come as close to KISS to prevent user error. Not only that, but I don't want any vague documentation if I can help it here. Since I feel like most other documentation I come across is too vague for it's own good to where it's no help.

2022-08-07 00:18 UTC, kaosine commented on docs/src/content/atom-server-side-apis/index.md
>  ## Atom server-side APIs
Which I'll probably create an archive section of the old docs once it runs without the path errors and the old tags that would never work here anyway.

2022-08-14 22:13 UTC, kaosine approved these changes
This definitely fixes my concerns. Going ahead and merging this now.

2022-08-14 22:13 UTC, merged